apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kartverket.vectortiles
  tags:
    - public
spec:
  type: website
  lifecycle: production
  owner: datadeling_og_distribusjon
  system: tjenester
